### ISSUE TITLE
publish package to pypi

### ISSUE THREAD

**Issue by joamatab** [dimapu/klayout_pyxs#10]
Hi Dima,

what do you think of publishing this package to PyPI?

so it's easier to install and interface with other packages

**Comment by joamatab** [comment]
Hi @dimapu,

any updates on this?

**Comment by dimapu** [comment]
@joamatab I'll try to figure it out myself, if I fail I will get back to you ;)

**Comment by joamatab** [comment]
I set up automatic CICD python upload to pypi in the fork and added you as a maintainer too

https://github.com/gdsfactory/klayout_pyxs/actions
